home:
  path: /index
  methods: ['GET']

client:
  path: /client/prenom/{prenom}
  controller: App\Controller\ClientController::info
  defaults:
    prenom: prenomDefaults
  requirements:
    prenom: "^[a-zA-Z](-?[a-zA-Z])*"

autre:
  path: /{suite}
  requirements:
    url: '[a-z]*'
